### ISSUE TITLE
ntdec_w parameter

### ISSUE THREAD

**Issue by zduputel** [OpenSWPC/OpenSWPC#17]
Not an issue per se... just a quick question about the ntdec_w parameter. From what I understand after a quick dive into the code, there is no filtering before undersampling the seismograms... Can you confirm that this is correct?

**Comment by tktmyd** [comment]
Hi @zduputel, thanks for your question. You are right, OpenSWPC does not perform any anti-aliasing filtering before decimating the waveform according to the `ntdec_w` parameter. So the `ntdec_w` parameter should be small enough compared to the inverse of the highest frequency of the simulation. Note that in the FDM calculation, the time step parameter (`dt`) tends to be very small even compared to the highest frequency of the waves, due to the constraint of the stability condition (CFL). Thus, a small number of `ntdec_w`, such as 2 to 10, depending on your velocity model and source time function, may be safe without being affected by aliasing effect and would be useful to reduce the amount of output data.

**Comment by zduputel** [comment]
Thanks for your quick reply.

**Comment by tktmyd** [comment]
You are welcome! I am closing this issue.
