### ISSUE TITLE
sourcetime function

### ISSUE THREAD

**Issue by adakite** [OpenSWPC/OpenSWPC#3]
Dear OpemSWPC devs'

I wonder how I can manage/change OPenSWPC for using my own source function which is for now existing as a force (X,Y,Z components) expressed in N as a function of time.  So basically I have something like: (t=i --> n) 
Fx_t=0 Fy_t=0 Fz_t=0
Fx_t=1 Fy_t=1 Fz_t=1
...
Fx_t=n Fy_t=n Fz_t=n

**Comment by tktmyd** [comment]
Hi, 

Please consider representing your time series of the single force (Fx(t), Fy(t), Fz(t)) by many single forces having a shape of a basis function. For this purpose, stype='triangle' source time function with a constant source duration $T_R$ and variable source starting time $T_0$. One single force source may represent at i-th time step, like 

> x y z (i-1)*dt 2*dt Fx(t_i) Fy(t_i) Fz(t_i)

in your source data file (fn_stf in the parameter, where dt is time increments of your source time function. In this case, your source (fn_stf) consists of N discrete sources. By choosing T_R = 2 *dt, one may represent smooth time series function by using the triangle basis function. Notice that amplitude of your $F_x, F_y, F_z$ should be adjusted, as the source time function is normalized so that its integration wrt time to be 1. 

Regards, 

Takuto
