### ISSUE TITLE
Near-field simulation + generating the velocity model

### ISSUE THREAD

**Issue by 79seismo** [OpenSWPC/OpenSWPC#8]
Dr. Maeda,
I have a couple of questions about OpenSWPC, hope you can answer:
(1) How do I create a NetCDF velocity model if I have a custom model in which lon, lat, depth, Vp, Vs, and rho are given?  I am guessing you are using GMT to convert an ascii file containing the velocity model to NetCDF format. Can you explain what the workflow is?

(2) How well are the near-field waves simulated? Can OpenSWPC used to predict strong ground motion in the vicinity of the source?

Thanks very much!

**Comment by tktmyd** [comment]
Hi 79seismo, 

(1) Yes, using GMT (commands such as xyz2grd, surface, triangulate) is one of the easiest way to create your own velocity model in grd format of OepnSWPC. Notice that a grd file in NetCDF format contains only depth information as a function of longitude and latitude. Other information, Vp, Vs, Density (also one need Qp and Qs) are given in the separate list file, and specify that list file as a parameter 'fn_grdlst'. See https://tktmyd.github.io/OpenSWPC/English/2._Parameter_Settings/0206_vmodel/ for detailed explanation. NetCDF files created by other tools or programming languages also should work fine with OpenSWPC. 

(2) I believe that output from the OpenSWPC is reliable regardless to the hypocenter distance, because it naturally includes near-field term as a part of the equation of motion. However it might be necessary that the FDM grid is fine enough compared to the source-station distance. 

Thank you, 

Takuto Maeda

**Comment by 79seismo** [comment]
Hi Dr. Maeda, 
Thanks very much. What's the best way to ask for help? Through GitHub? or is there an email address I can write to? 

Januka Attanayake
University of Melbourne

**Comment by tktmyd** [comment]
Dear Januka, 

I prefer through GitHub so that I can share your question with my development collaborators. Thanks!

Takuto
